config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # get 'tasks', to: 'tasks#index'
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
  resources :tasks, only: [:create, :index, :edit, :update, :new, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @task = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save
    redirect_to task_path(@task.id)
  end

  def edit
  end

  def update
    @task.update(tasks_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :details)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<p><%= link_to 'Delete task', task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>

<p><%= link_to 'Back to list', tasks_path %></p>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @task.each do |t| %>
    <li>
      <%= link_to t.title, task_path(t.id) %> -
      <%= link_to 'Delete task', delete_task_path(t.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </li>
  <% end %>
</ul>

<p><%= link_to "+ Add a new task", new_task_path %></p>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<p><%= link_to 'Back to list', tasks_path %></p>

app/views/tasks/show.html.erb
<h1>Task <%= @task.title %> detail</h1>

<p><%= @task.details %></p>

<p><%= link_to 'Delete task', task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>

<p><%= link_to 'Edit this task', edit_task_path(@task.id) %></p>

<p><%= link_to 'Back to list', tasks_path %></p>